CREATE TABLE author(id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255), email VARCHAR(255) NOT NULL UNIQUE, password VARCHAR(255), created_time DATETIME DEFAULT current_timestamp);

CREATE TABLE post(id INT AUTO_INCREMENT PRIMARY KEY, title VARCHAR(255) NOT NULL, contents VARCHAR(255));

CREATE TABLE author_address(id INT AUTO_INCREMENT PRIMARY KEY, city VARCHAR(255), street VARCHAR(255), author_id VARCHAR(255));
ALTER TABLE author_address ADD CONSTRAINT author_address_fk FOREIGN()

