CREATE TABLE author(id INT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(255),
email VARCHAR(255) NOT NULL UNIQUE, created_time DATETIME DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE post(id INT PRIMARY KEY AUTO_INCREMENT,
title VARCHAR(255) NOT NULL, contents VARCHAR(255));

CREATE TABLE author_address(id INT PRIMARY KEY AUTO_INCREMENT, city VARCHAR(255),
street VARCHAR(255), author_id int NOT NULL,
UNIQUE(author_id), FOREIGN KEY(author_id) REFERENCES author(id) ON DELETE CASCADE);

CREATE TABLE author_post(id INT PRIMARY KEY AUTO_INCREMENT,
author_id int NOT NULL, post_id int NOT NULL,
FOREIGN KEY(author_id) REFERENCES author(id),
FOREIGN KEY(post_id) REFERENCES post(id));
